import '../styles/main.css';
import Footer from '../components/layout/Footer';
import Header from '../components/layout/Header';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  )
}
